name: Build Clean Kernel Samsung A32 (Scamsung)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc libncurses5-dev libssl-dev bison flex libelf-dev zip ccache glibc-source clang libssl-dev python3 python-is-python3

    - name: Download AOSP Toolchain (Clang & GCC)
      run: |
        mkdir -p toolchain
        cd toolchain
        # Download AOSP Clang r383902 dari GitHub publik
        git clone --depth=1 https://github.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-6443078.git clang
        # Download GCC 64-bit & 32-bit AOSP
        git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9.git gcc64
        git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9.git gcc32

    - name: Compile Kernel
      run: |
        mkdir -p out
        
        export PATH="$(pwd)/toolchain/clang/bin:$(pwd)/toolchain/gcc64/bin:$(pwd)/toolchain/gcc32/bin:$PATH"
        
        export ARCH=arm64
        export SUBARCH=arm64
        
        # 1. Generate Config
        make O=out ARCH=arm64 a32_defconfig
        
        # 2. Proses Build Kernel & Set Nama Scamsung
        make -j$(nproc --all) O=out ARCH=arm64 \
          CC=clang \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CROSS_COMPILE=aarch64-linux-android- \
          CROSS_COMPILE_ARM32=arm-linux-androideabi- \
          LOCALVERSION="-Scamsung"

    - name: Package with AnyKernel3
      run: |
        git clone --depth=1 https://github.com/osm0sis/AnyKernel3 AnyKernel3
        
        if [ -f out/arch/arm64/boot/Image.gz-dtb ]; then
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
        elif [ -f out/arch/arm64/boot/Image.gz ]; then
          cp out/arch/arm64/boot/Image.gz AnyKernel3/
        elif [ -f out/arch/arm64/boot/Image ]; then
          cp out/arch/arm64/boot/Image AnyKernel3/
        fi
        
        cd AnyKernel3
        zip -r9 ../Scamsung-Kernel-A32.zip * -x .git README.md

    - name: Upload Kernel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Scamsung-Kernel-A32
        path: Scamsung-Kernel-A32.zip
